[package]
name = "openpid"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
toml = "0.8.10"
