direction: right
sensors {
    peripheral 1
    peripheral 2
    peripheral 3
    peripheral 4
}

platforms {
    platforms 1
    platforms 2
    platforms 3
    platforms 4
}

sensors.peripheral 1 <-> platforms.platforms 1
sensors.peripheral 1 <-> platforms.platforms 2
sensors.peripheral 1 <-> platforms.platforms 3
sensors.peripheral 1 <-> platforms.platforms 4

sensors.peripheral 2 <-> platforms.platforms 1
sensors.peripheral 2 <-> platforms.platforms 2
sensors.peripheral 2 <-> platforms.platforms 3
sensors.peripheral 2 <-> platforms.platforms 4

sensors.peripheral 3 <-> platforms.platforms 1
sensors.peripheral 3 <-> platforms.platforms 2
sensors.peripheral 3 <-> platforms.platforms 3
sensors.peripheral 3 <-> platforms.platforms 4

sensors.peripheral 4 <-> platforms.platforms 1
sensors.peripheral 4 <-> platforms.platforms 2
sensors.peripheral 4 <-> platforms.platforms 3
sensors.peripheral 4 <-> platforms.platforms 4
