[device_info]
name = "TargetPoint3"
description = "PNI Sensor TargetPoint3 Serial Interface"

[packet_formats]
send = [ 
    { type = "SizeTotal", size_bits = 8, express_as = "Bytes" },
    { type = "Metadata", key = "FrameID" },
    { type = "Payload" },
    { type = "Crc", algorithm = "Crc16XModem" },
]

recieve = [ 
    { type = "SizeTotal", size_bits = 8, express_as = "Bytes" },
    { type = "Metadata", key = "FrameID" },
    { type = "Payload" },
    { type = "Crc", algorithm = "Crc16XModem" },
]

[structs]

[payloads.send.GetModInfo]
description = "This frame queries the device's type and firmware revision number. The frame has no payload."
segments = []
FrameID = { name = "FrameID", type = "Raw", bits = 8 }

[payloads.recieve.GetModInfoResp]
description = "Response to GetModInfo"
FrameID = { name = "FrameID", type = "Raw", bits = 8 }
segments = [
#    { name = "type", bits = 32, type = { type = "Integer", endianness = "BigEndian" } },
    { name = "type", bits = 32, type = "StringUTF8" },
    { name = "revision", bits = 32, type = "StringUTF8" }
]

[transactions.GetModInfo]
description = "Gets device type and firmware revision number"
actions = [
    {type = "Tx", payload = "GetModInfo"},
    {type = "Rx", payload = "GetModInfoResp"},
]
returns = ["GetModInfoResp.type", "GetModInfoResp.revision"]
