Web {
    Open API Spec 
    Web Backend
    Open API Spec -> Web Frontend SDK: codegen
}
sensorapi -> documentation: docgen
sensorapi -> rust embedded_hal SDK: codegen
sensorapi -> C SDK: codegen
sensorapi -> GUI Playground: codegen
sensorapi -> Logging Frontend: codegen
sensorapi -> Web: codegen
