grid-rows: 1
grid-gap: 0

vars: {
  d2-config: {
    layout-engine: dagre
    theme-id: 4
  }
}
  

1: 8 bits
2: 8 bits
3: Variable
4: 16 bits

1: {
  explanation: |md Size |
  explanation.style.font-size: 55

  style.font-size: 40
}

2: {
  explanation: |md FrameID |
  explanation.style.font-size: 55

  style.font-size: 40
}

3: {
  explanation: |md Payload |
  explanation.style.font-size: 55

  style.font-size: 40
}

4: {
  explanation: |md Crc |
  explanation.style.font-size: 55

  style.font-size: 40
}
